class Chronify < Formula
  include Language::Python::Virtualenv

  desc "Menu bar work tracker with local-AI daily statuses and invoicing"
  homepage "https://github.com/zepuff/Chronify"
  url "https://github.com/zepuff/Chronify/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "27a8a72da084f08a284fb589aeec3e97bcd2da9aef9d6712d98986343a838c57"
  license "GPL-3.0-or-later"

  depends_on "python@3.13"
  depends_on :macos

  # The resources below are prebuilt wheels rather than source archives, so
  # nothing is compiled here and the C libraries those builds used to need
  # (freetype, libxml2, libyaml and the rest) are no longer dependencies.
  #
  # A wheel is tied to one Python version, which is why python@3.13 above is
  # pinned. To move to another Python, regenerate this block from the project
  # repository:
  #
  #     python3 packaging/wheels.py --python 3.14
  #
  # Do not run `brew update-python-resources` on this formula: it would put
  # source archives back and the twenty minute install with them.

  # --- generated resources: start ---
  # Wheels for Python 3.13, generated by packaging/wheels.py.
  # Re-run it when the formula moves to another Python.

  resource "certifi" do
    url "https://files.pythonhosted.org/packages/0b/a7/71ac2cff56fec219ed242bb11b8efb69fcc4bec75db06fb7bfe35de520e6/certifi-2026.7.22-py3-none-any.whl", using: :nounzip
    sha256 "62f22742b58a1a33014a2b6b706588a8d7e2a88ae7bd1a6ebe8c992928483775"
  end

  resource "charset-normalizer" do
    url "https://files.pythonhosted.org/packages/a4/a0/562247944386f7d4ef94467e84876600cc1e0f1b93239aaa9213d2bc3cbd/charset_normalizer-3.5.1-cp313-cp313-macosx_10_13_universal2.whl", using: :nounzip
    sha256 "e90251c0c7bdd54a100a0dce3c07b7e637278c93af29dbf78ebb89a58c4bac7d"
  end

  resource "docxtpl" do
    url "https://files.pythonhosted.org/packages/a4/ad/e07939d8e020e513d3860400413ba1e0e06102c469639b440d921337efef/docxtpl-0.20.2-py3-none-any.whl", using: :nounzip
    sha256 "626d5c570a46a62b2ca73b4d08f1c240fa031a5bc45371e1466a4fe184923d10"
  end

  resource "idna" do
    url "https://files.pythonhosted.org/packages/58/a2/bb081bab032533a855d44de1d56f8e8426114ff1ba5d1f07a438a0a654f8/idna-3.20-py3-none-any.whl", using: :nounzip
    sha256 "ab7ae7122974553370f0bdb919e1a960b2cd1bc1ef0276416d896db81c14582c"
  end

  resource "jinja2" do
    url "https://files.pythonhosted.org/packages/62/a1/3d680cbfd5f4b8f15abc1d571870c5fc3e594bb582bc3b64ea099db13e56/jinja2-3.1.6-py3-none-any.whl", using: :nounzip
    sha256 "85ece4451f492d0c13c5dd7c13a64681a86afae63a5f347908daf103ce6d2f67"
  end

  resource "packaging" do
    url "https://files.pythonhosted.org/packages/63/34/ba1c580383c9eada3711951fef0795c80b829a078d72188184bcab9dd527/packaging-26.3-py3-none-any.whl", using: :nounzip
    sha256 "d7193f7c8e4e93f444fde0262bf90af30e16fa0ad0ad44cb553c87339b23cd1c"
  end

  resource "pyobjc-core" do
    url "https://files.pythonhosted.org/packages/1b/ed/a8bf040caf3704023d74086b7fb96cf4ed2e844e24bd94e5248ba214b700/pyobjc_core-12.2.2-cp313-cp313-macosx_10_13_universal2.whl", using: :nounzip
    sha256 "950bd2d9c74634398c4e3d24ef2f213d4e23d705083697464fa67afedc53c1ad"
  end

  resource "pyobjc-framework-cocoa" do
    url "https://files.pythonhosted.org/packages/db/e1/5d9b04ebb60042b9cb49adc2d33115e2f2c2e4ff7d548017bfaff8b7f536/pyobjc_framework_cocoa-12.2.2-cp313-cp313-macosx_10_13_universal2.whl", using: :nounzip
    sha256 "600b1723184ca094931330e79355274949965460e23de38628d601b5a967baf9"
  end

  resource "pyobjc-framework-quartz" do
    url "https://files.pythonhosted.org/packages/bb/ae/b515852dbe491171f2f2e2eb7739588a5eb7f36720a739545337b8c0d706/pyobjc_framework_quartz-12.2.2-cp313-cp313-macosx_10_13_universal2.whl", using: :nounzip
    sha256 "0ec9751904ef975bf0789d760dc4fadcb400edc4ffe4a736eb54971968babe5c"
  end

  resource "python-docx" do
    url "https://files.pythonhosted.org/packages/d0/00/1e03a4989fa5795da308cd774f05b704ace555a70f9bf9d3be057b680bcf/python_docx-1.2.0-py3-none-any.whl", using: :nounzip
    sha256 "3fd478f3250fbbbfd3b94fe1e985955737c145627498896a8a6bf81f4baf66c7"
  end

  resource "requests" do
    url "https://files.pythonhosted.org/packages/a0/f4/c67b0b3f1b9245e8d266f0f112c500d50e5b4e83cb6f3b71b6528104182a/requests-2.34.2-py3-none-any.whl", using: :nounzip
    sha256 "2a0d60c172f83ac6ab31e4554906c0f3b3588d37b5cb939b1c061f4907e278e0"
  end

  resource "setuptools" do
    url "https://files.pythonhosted.org/packages/95/9c/c510029fc6ef33a6275cd2c5d3cecd6613dfd6aa401d57c54f1c18852ccf/setuptools-84.0.0-py3-none-any.whl", using: :nounzip
    sha256 "51a52592b3b99e102b609654876bd65f19f999935166d1352678931132b0c670"
  end

  resource "typing-extensions" do
    url "https://files.pythonhosted.org/packages/49/d3/b8441a820a491ddfc024b0b0cf0393375b75ea13866d9c66727e54c2fc80/typing_extensions-4.16.0-py3-none-any.whl", using: :nounzip
    sha256 "481caa481374e813c1b176ada14e97f1f67a4539ce9cfeb3f350d78d6370c2e8"
  end

  resource "urllib3" do
    url "https://files.pythonhosted.org/packages/92/9d/c4e665119135114480843e7ab388fa94d8480650450e6f8e26b70d323a4c/urllib3-2.8.0-py3-none-any.whl", using: :nounzip
    sha256 "0cf3cae568d36aa9576b28dfb35f11328f1cb974ca7647d9475ebb86c75ac6e3"
  end

  resource "wheel" do
    url "https://files.pythonhosted.org/packages/2e/29/69cfbb602cd91690c55d38ba9fe53e6a7e76a6fa647bf38f19c138d25449/wheel-0.48.0-py3-none-any.whl", using: :nounzip
    sha256 "3217dcc807155e45db462d7ef2431f5ddda0d7273b700d05a67b271ceb1287ab"
  end

  resource "rumps" do
    url "https://files.pythonhosted.org/packages/b2/e2/2e6a47951290bd1a2831dcc50aec4b25d104c0cf00e8b7868cbd29cf3bfe/rumps-0.4.0.tar.gz"
    sha256 "17fb33c21b54b1e25db0d71d1d793dc19dc3c0b7d8c79dc6d833d0cffc8b1596"
  end

  on_arm do
    resource "lxml" do
      url "https://files.pythonhosted.org/packages/52/05/3ef45db776baea068044c799bbba68f3ca00a440c0e930a17c572f3d9639/lxml-6.1.3-cp313-cp313-macosx_10_13_universal2.whl", using: :nounzip
      sha256 "3a48093cdb058a93af842ede9703520e810b05dcd0fc6d7190a06376c3bfb6bd"
    end

    resource "markupsafe" do
      url "https://files.pythonhosted.org/packages/9c/d9/5f7756922cdd676869eca1c4e3c0cd0df60ed30199ffd775e319089cb3ed/markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl", using: :nounzip
      sha256 "116bb52f642a37c115f517494ea5feb03889e04df47eeff5b130b1808ce7c219"
    end

    resource "pillow" do
      url "https://files.pythonhosted.org/packages/10/76/8803c13605b763d33d156c4678fc77f8443389c0c51c8aef707bb02015f4/pillow-12.3.0-cp313-cp313-macosx_11_0_arm64.whl", using: :nounzip
      sha256 "d69141514cc30b774ceea5e3ed3a6635c8d8a96edf664689b890f4089111fb35"
    end

    resource "pyyaml" do
      url "https://files.pythonhosted.org/packages/b1/16/95309993f1d3748cd644e02e38b75d50cbc0d9561d21f390a76242ce073f/pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl", using: :nounzip
      sha256 "2283a07e2c21a2aa78d9c4442724ec1eb15f5e42a723b99cb3d822d48f5f7ad1"
    end

  end

  on_intel do
    resource "lxml" do
      url "https://files.pythonhosted.org/packages/8c/a5/eee2fc77eee5ea68e4a4334b1def1781a3beaeefd3d98e81b4a38dc447b7/lxml-6.1.3-cp313-cp313-macosx_10_13_x86_64.whl", using: :nounzip
      sha256 "887c021d9a977cff89cb273047c1352997b772a8908a25c21836861f69b92be1"
    end

    resource "markupsafe" do
      url "https://files.pythonhosted.org/packages/38/2f/907b9c7bbba283e68f20259574b13d005c121a0fa4c175f9bed27c4597ff/markupsafe-3.0.3-cp313-cp313-macosx_10_13_x86_64.whl", using: :nounzip
      sha256 "e1cf1972137e83c5d4c136c43ced9ac51d0e124706ee1c8aa8532c1287fa8795"
    end

    resource "pillow" do
      url "https://files.pythonhosted.org/packages/42/92/2fc3ffad878ae8dd5469ec1bc8eb83b71f48e13efdf68f02709003982a32/pillow-12.3.0-cp313-cp313-macosx_10_13_x86_64.whl", using: :nounzip
      sha256 "7a743ff716f746fc19a9557f60dab1600d4613255f8a7aeb3cdde4db7eb15a66"
    end

    resource "pyyaml" do
      url "https://files.pythonhosted.org/packages/d1/11/0fd08f8192109f7169db964b5707a2f1e8b745d4e239b784a5a1dd80d1db/pyyaml-6.0.3-cp313-cp313-macosx_10_13_x86_64.whl", using: :nounzip
      sha256 "8da9669d359f02c0b91ccc01cac4a67f16afec0dac22c2ad09f46bee0697eba8"
    end

  end
  # --- generated resources: end ---

  def install
    venv = virtualenv_create(libexec, "python3.13")

    wheelhouse = buildpath/"wheelhouse"
    wheelhouse.mkpath
    sources = []

    resources.each do |r|
      r.stage do
        wheels = Dir["*.whl"]
        if wheels.any?
          cp wheels, wheelhouse
        else
          # rumps publishes a source archive only. It is pure Python, so this
          # costs a second and needs no compiler.
          kept = buildpath/"sources"/r.name
          kept.mkpath
          cp_r Dir["*"], kept
          sources << kept
        end
      end
    end

    # The virtualenv is created with --without-pip, so there is no bin/pip to
    # call. Running it as a module works because --system-site-packages lets
    # the environment see the pip that comes with python@3.13.
    python = libexec/"bin/python"
    offline = ["--no-index", "--find-links", wheelhouse.to_s]

    system python, "-m", "pip", "install", *offline, "--no-deps",
           "setuptools", "wheel"

    sources.each do |path|
      system python, "-m", "pip", "wheel", "--no-deps", "--no-build-isolation",
             "--wheel-dir", wheelhouse, path
    end

    system python, "-m", "pip", "install", *offline, "--no-deps",
           *Dir[wheelhouse/"*.whl"]

    venv.pip_install_and_link buildpath
  end

  service do
    run opt_bin/"chronify"
    keep_alive crashed: true
    log_path var/"log/chronify.log"
    error_log_path var/"log/chronify.log"
  end

  def caveats
    tty = $stdout.tty?
    b   = tty ? "\e[1m"    : ""   # bold
    h   = tty ? "\e[1;36m" : ""   # bold cyan, for headings
    g   = tty ? "\e[1;32m" : ""   # bold green, for things to type
    d   = tty ? "\e[2m"    : ""   # dim, for asides
    r   = tty ? "\e[0m"    : ""   # reset

    <<~EOS
      #{b}Chronify is the ⏱ clock that now lives in your menu bar.#{r}
      It watches which window is in front and writes your workday down for you:
      hours per task, a daily status built from your own rough notes, and the
      numbers your timesheet and invoice need at the end of the month.
      #{d}Everything stays on this Mac. No account, no cloud, no API key.#{r}

      #{d}Made for people who bill by the hour: contractors, freelancers, anyone
      who has to say what they did today and how long it took.#{r}

      #{h}START HERE. Three steps, about two minutes#{r}
        #{g}1.#{r} #{g}chronify --background#{r}
           Starts it and gives this terminal back. Plain `chronify` runs it
           here instead, where Ctrl+C quits it.

        #{g}2.#{r} #{b}Allow Screen Recording#{r} when macOS asks
           Without it window titles are invisible and your whole day is logged
           as bare app names with no task breakdown. Quit and start Chronify
           again afterwards, macOS only reads that permission at launch.

        #{g}3.#{r} #{b}⏱ → 🏷 Project → + Add a project#{r}
           Every hour belongs to a project, so nothing is recorded until one
           exists. Only the name is required.

      #{h}THEN, EVERY DAY#{r}
        during the day   #{b}⏱ → ✅ What I did today#{r}
                         #{d}one line per finished thing, written however it comes out#{r}
        in the evening   #{b}⏱ → ✨ Write today's status#{r}
                         #{d}turns those lines into text you can paste into Slack#{r}
        end of month     #{b}⏱ → 🧾 Invoice#{r} and #{b}📤 Send hours to PeopleForce#{r}

      #{d}Every item in the menu carries a small grey line explaining what it
      does, so you can read the menu instead of the manual.#{r}

      #{h}OPTIONAL#{r}
        #{g}brew services start chronify#{r}        start it at every login
        #{g}brew install --cask libreoffice#{r}     PDF export for invoices
        A local model that rewrites your notes: #{b}⚙️ Settings → Daily status#{r}
        #{d}picks it and installs it for you, nothing to do by hand.#{r}

      #{h}WHERE THINGS LIVE#{r}
        #{b}~/.work_tracker/#{r}  settings, database, statuses. The one folder to
        back up. config.yaml is created there on the first run and upgrades
        never touch it.

      #{h}THE GUIDE#{r}
        #{b}https://zepuff.github.io/Chronify/#{r}
    EOS
  end

  test do
    assert_match "chronify #{version}", shell_output("#{bin}/chronify --version")
  end
end
